"""update user/chat schema

Revision ID: 424180563193
Revises: 
Create Date: 2025-05-10 23:26:07.861449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '424180563193'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_message', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('chat_message', 'user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('chat_message', 'session_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('chat_message', 'role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('user', 'assistant', 'system'),
               nullable=False)
    op.alter_column('chat_message', 'message',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('chat_message', 'timestamp',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('chat_message_ibfk_2', 'chat_message', type_='foreignkey')
    op.drop_constraint('chat_message_ibfk_1', 'chat_message', type_='foreignkey')
    op.create_foreign_key(None, 'chat_message', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'chat_message', 'chat_session', ['session_id'], ['id'])
    op.alter_column('chat_session', 'id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('chat_session', 'user_id',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               nullable=False)
    op.alter_column('chat_session', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_session', 'last_active',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('chat_session_ibfk_1', 'chat_session', type_='foreignkey')
    op.create_foreign_key(None, 'chat_session', 'user', ['user_id'], ['id'])
    op.add_column('user', sa.Column('id', sa.String(length=36), nullable=False))
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=False))
    op.add_column('user', sa.Column('password_hash', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('class_name', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('role', sa.Enum('user', 'admin', 'moderator'), nullable=False))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=120),
               nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'updated_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_unique_constraint(None, 'user', ['username'])
    op.drop_column('user', 'password')
    op.drop_column('user', 'class')
    op.drop_column('user', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_id', mysql.CHAR(length=36), nullable=False))
    op.add_column('user', sa.Column('class', mysql.TEXT(), nullable=True))
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'updated_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('user', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user', 'email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user', 'role')
    op.drop_column('user', 'class_name')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'username')
    op.drop_column('user', 'id')
    op.drop_constraint(None, 'chat_session', type_='foreignkey')
    op.create_foreign_key('chat_session_ibfk_1', 'chat_session', 'user', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('chat_session', 'last_active',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('chat_session', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_session', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               nullable=True)
    op.alter_column('chat_session', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.create_foreign_key('chat_message_ibfk_1', 'chat_message', 'user', ['user_id'], ['user_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('chat_message_ibfk_2', 'chat_message', 'chat_session', ['session_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('chat_message', 'timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_message', 'message',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('chat_message', 'role',
               existing_type=sa.Enum('user', 'assistant', 'system'),
               type_=mysql.VARCHAR(length=20),
               nullable=True)
    op.alter_column('chat_message', 'session_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               nullable=True)
    op.alter_column('chat_message', 'user_id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               nullable=True)
    op.alter_column('chat_message', 'id',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###
